/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Bean.UserBean;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Elifelia
 */
public class FormUtama extends javax.swing.JFrame {
    UserBean temp;

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        purchasingMenuBar = new javax.swing.JMenu();
        purchaseRequestMenu = new javax.swing.JMenu();
        purchaseRequestForm = new javax.swing.JMenuItem();
        purchaseRequestView = new javax.swing.JMenuItem();
        purchaseOrderMenu = new javax.swing.JMenu();
        purchaseOrderForm = new javax.swing.JMenuItem();
        purchaseOrderView = new javax.swing.JMenuItem();
        PurchaseOrderInactiving = new javax.swing.JMenuItem();
        receivingMenu = new javax.swing.JMenu();
        receivingForm = new javax.swing.JMenuItem();
        receivingView = new javax.swing.JMenuItem();
        masterDataMenuBar = new javax.swing.JMenu();
        department = new javax.swing.JMenuItem();
        item = new javax.swing.JMenuItem();
        category = new javax.swing.JMenuItem();
        user = new javax.swing.JMenuItem();
        measure = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        currency = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchasing System");
        setResizable(false);

        jLabel3.setText("Citra Dream Hotel Yogyakarta");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corner.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel6.setText("Purchasing System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)))
                .addGap(33, 33, 33)
                .addComponent(jLabel4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4))
        );

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(15, 15, 15))
        );

        jLabel7.setText("jLabel7");
        jLabel7.setVisible(false);

        logout.setText("Logout");
        logout.setVisible(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout))
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        purchasingMenuBar.setText("Purchasing");
        purchasingMenuBar.setEnabled(false);

        purchaseRequestMenu.setText("Purchase Request");

        purchaseRequestForm.setText("Purchase Request Form");
        purchaseRequestForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseRequestFormActionPerformed(evt);
            }
        });
        purchaseRequestMenu.add(purchaseRequestForm);

        purchaseRequestView.setText("Purchase Request View");
        purchaseRequestView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseRequestViewActionPerformed(evt);
            }
        });
        purchaseRequestMenu.add(purchaseRequestView);

        purchasingMenuBar.add(purchaseRequestMenu);

        purchaseOrderMenu.setText("Purchase Order");

        purchaseOrderForm.setText("Purchase Order Form");
        purchaseOrderForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderFormActionPerformed(evt);
            }
        });
        purchaseOrderMenu.add(purchaseOrderForm);

        purchaseOrderView.setText("Purchase Order View");
        purchaseOrderMenu.add(purchaseOrderView);

        PurchaseOrderInactiving.setText("Purchase Order Inactiving");
        PurchaseOrderInactiving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseOrderInactivingActionPerformed(evt);
            }
        });
        purchaseOrderMenu.add(PurchaseOrderInactiving);

        purchasingMenuBar.add(purchaseOrderMenu);

        receivingMenu.setText("Receiving");

        receivingForm.setText("Receiving Form");
        receivingMenu.add(receivingForm);

        receivingView.setText("Receiving View");
        receivingMenu.add(receivingView);

        purchasingMenuBar.add(receivingMenu);

        jMenuBar1.add(purchasingMenuBar);

        masterDataMenuBar.setText("Master Data");
        masterDataMenuBar.setEnabled(false);

        department.setText("Department");
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(department);

        item.setText("Item");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(item);

        category.setText("Category");
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(category);

        user.setText("User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(user);

        measure.setText("Measure");
        measure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                measureActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(measure);

        jMenuItem12.setText("Supplier");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(jMenuItem12);

        currency.setText("Currency");
        currency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyActionPerformed(evt);
            }
        });
        masterDataMenuBar.add(currency);

        jMenuBar1.add(masterDataMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseRequestFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseRequestFormActionPerformed
        // TODO add your handling code here:
        PurchaseRequest pr  = new PurchaseRequest(temp.getDept_id());
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_purchaseRequestFormActionPerformed

    private void purchaseRequestViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseRequestViewActionPerformed
        // TODO add your handling code here:
//        PurchaseRequest pr  = new PurchaseRequest();
//        pr.setVisible(true);
//        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_purchaseRequestViewActionPerformed

    private void purchaseOrderFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderFormActionPerformed
        // TODO add your handling code here:
        PurchaseOrder po  = new PurchaseOrder();
        po.setVisible(true);
        po.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        po.getComponents().
    }//GEN-LAST:event_purchaseOrderFormActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
        MasterDept d  = new MasterDept();
        d.setVisible(true);
        d.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_departmentActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
        MasterItem pr  = new MasterItem();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
        MasterCategory pr  = new MasterCategory();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_categoryActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        UserAdd pr  = new UserAdd();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_userActionPerformed

    private void measureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_measureActionPerformed
        // TODO add your handling code here:
        MasterMeasure pr  = new MasterMeasure();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_measureActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        SuppliersAdd pr  = new SuppliersAdd();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void currencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyActionPerformed
        // TODO add your handling code here:
        MasterCurrency pr  = new MasterCurrency();
        pr.setVisible(true);
        pr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_currencyActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        UserBean ub  = new UserBean();
        
        temp = ub.cariUser(usernameField.getText(), passwordField.getText());
        if (ub.login(temp)) {
            JOptionPane.showMessageDialog(null, "Login Success!");
            purchasingMenuBar.setEnabled(true);
            masterDataMenuBar.setEnabled(true);
            jInternalFrame1.setVisible(false);
            jLabel7.setText("Welcome, "+temp.getUser_name());
            jLabel7.setVisible(true);
            logout.setVisible(true);
            purchaseOrderForm.setEnabled(temp.getPurchaseOrd());
            purchaseOrderView.setEnabled(temp.getPurchaseOrdView());
            purchaseRequestForm.setEnabled(temp.getPurchaseReq());
            purchaseRequestView.setEnabled(temp.getPurchaseReqView());
            PurchaseOrderInactiving.setEnabled(temp.getPurchaseOrdInactive());
            receivingForm.setEnabled(temp.getReceiving());
            receivingView.setEnabled(temp.getReceivingView());
            masterDataMenuBar.setEnabled(temp.getMasterData());
            ub.dataLoginFile(temp.getUser_name(), temp.getDept_id());
            
        }else{
            JOptionPane.showMessageDialog(null, "Login failed, Check your Username and Password");
            usernameField.setText(null);
            passwordField.setText(null);
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showConfirmDialog(null, "Are you want to Logout from system?");
        purchasingMenuBar.setEnabled(false);
        masterDataMenuBar.setEnabled(false);
        jInternalFrame1.setVisible(true);
        jLabel7.setVisible(false);
        logout.setVisible(false);
        usernameField.setText(null);
        passwordField.setText(null);
    }//GEN-LAST:event_logoutActionPerformed

    private void PurchaseOrderInactivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseOrderInactivingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchaseOrderInactivingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PurchaseOrderInactiving;
    private javax.swing.JMenuItem category;
    private javax.swing.JMenuItem currency;
    private javax.swing.JMenuItem department;
    private javax.swing.JMenuItem item;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logout;
    private javax.swing.JMenu masterDataMenuBar;
    private javax.swing.JMenuItem measure;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JMenuItem purchaseOrderForm;
    private javax.swing.JMenu purchaseOrderMenu;
    private javax.swing.JMenuItem purchaseOrderView;
    private javax.swing.JMenuItem purchaseRequestForm;
    private javax.swing.JMenu purchaseRequestMenu;
    private javax.swing.JMenuItem purchaseRequestView;
    private javax.swing.JMenu purchasingMenuBar;
    private javax.swing.JMenuItem receivingForm;
    private javax.swing.JMenu receivingMenu;
    private javax.swing.JMenuItem receivingView;
    private javax.swing.JMenuItem user;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
